# Generated by Django 2.2.2 on 2019-06-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emaillist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillist',
            old_name='email',
            new_name='emailll',
        ),
    ]
