# Generated by Django 2.2.2 on 2019-06-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emaillist', '0002_auto_20190620_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillist',
            old_name='emailll',
            new_name='email',
        ),
    ]
